/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EquivalentsRouteImport } from './routes/equivalents'
import { Route as GearRouteImport } from './routes/gear'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ApiKeepaliveRouteImport } from './routes/api/keepalive'
import { Route as PresetIdRouteImport } from './routes/preset.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EquivalentsRoute = EquivalentsRouteImport.update({
  id: '/equivalents',
  path: '/equivalents',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetIdRoute = PresetIdRouteImport.update({
  id: '/preset/$id',
  path: '/preset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/preset/$id': typeof PresetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/preset/$id': typeof PresetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/preset/$id': typeof PresetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/guide'
    | '/history'
    | '/login'
    | '/settings'
    | '/upgrade'
    | '/api/keepalive'
    | '/preset/$id'
    | '/api/auth/$'
    | '/api/polar/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/guide'
    | '/history'
    | '/login'
    | '/settings'
    | '/upgrade'
    | '/api/keepalive'
    | '/preset/$id'
    | '/api/auth/$'
    | '/api/polar/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/guide'
    | '/history'
    | '/login'
    | '/settings'
    | '/upgrade'
    | '/api/keepalive'
    | '/preset/$id'
    | '/api/auth/$'
    | '/api/polar/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  CreateRoute: typeof CreateRoute
  EquivalentsRoute: typeof EquivalentsRoute
  GearRoute: typeof GearRoute
  GuideRoute: typeof GuideRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  UpgradeRoute: typeof UpgradeRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  PresetIdRoute: typeof PresetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equivalents': {
      id: '/equivalents'
      path: '/equivalents'
      fullPath: '/equivalents'
      preLoaderRoute: typeof EquivalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preset/$id': {
      id: '/preset/$id'
      path: '/preset/$id'
      fullPath: '/preset/$id'
      preLoaderRoute: typeof PresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  CreateRoute: CreateRoute,
  EquivalentsRoute: EquivalentsRoute,
  GearRoute: GearRoute,
  GuideRoute: GuideRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  UpgradeRoute: UpgradeRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  PresetIdRoute: PresetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
