/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EquivalentsRouteImport } from './routes/equivalents'
import { Route as GearRouteImport } from './routes/gear'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PresetIdRouteImport } from './routes/preset.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EquivalentsRoute = EquivalentsRouteImport.update({
  id: '/equivalents',
  path: '/equivalents',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetIdRoute = PresetIdRouteImport.update({
  id: '/preset/$id',
  path: '/preset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/preset/$id': typeof PresetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/preset/$id': typeof PresetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/create': typeof CreateRoute
  '/equivalents': typeof EquivalentsRoute
  '/gear': typeof GearRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/preset/$id': typeof PresetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/history'
    | '/settings'
    | '/preset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/history'
    | '/settings'
    | '/preset/$id'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/create'
    | '/equivalents'
    | '/gear'
    | '/history'
    | '/settings'
    | '/preset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CreateRoute: typeof CreateRoute
  EquivalentsRoute: typeof EquivalentsRoute
  GearRoute: typeof GearRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  PresetIdRoute: typeof PresetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equivalents': {
      id: '/equivalents'
      path: '/equivalents'
      fullPath: '/equivalents'
      preLoaderRoute: typeof EquivalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preset/$id': {
      id: '/preset/$id'
      path: '/preset/$id'
      fullPath: '/preset/$id'
      preLoaderRoute: typeof PresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CreateRoute: CreateRoute,
  EquivalentsRoute: EquivalentsRoute,
  GearRoute: GearRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  PresetIdRoute: PresetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
